'use client'

import { useState } from "react";
import Products from "@/components/Products";
import Sidebar from "@/components/Sidebar";

export default function Home() {
  const [selectedCategory, setSelectedCategory] = useState('');
  const [maxPrice, setMaxPrice] = useState(1000);

  return (
    <>
      <div className="main-container flex px-5 my-10 mx-auto gap-5">
        <Sidebar selectedCategory={selectedCategory}
          setSelectedCategory={setSelectedCategory}
          maxPrice={maxPrice}
          setMaxPrice={setMaxPrice} />

        <Products
          selectedCategory={selectedCategory}
          maxPrice={maxPrice} />
      </div>
    </>
  );
}


// export const metadata = {
//   title: "Whatbytes | Home",
//   description: "Generated by create next app",
// };