import Products from "@/components/Products";
import Sidebar from "@/components/Sidebar";

export default function Home() {
  return (
    <>
      <div className="main-container flex px-5 my-10 mx-auto gap-5">
        <Sidebar />
        <Products />
      </div>
    </>
  );
}


export const metadata = {
  title: "Whatbytes | Home",
  description: "Generated by create next app",
};